;;; yae_simple

;; Copyright (C) 2024

;; Author: Yilkal Argaw

;; This file is part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

;;; Code:

;;;###theme-autoload

(defgroup yae-simple-theme nil
  "Custom theme settings for YAE."
  :group 'faces)

(defcustom yae-color-palettes
  '((palenight
     . ((yae-ansi-black         . "#292d3e")
        (yae-ansi-blue          . "#82aaff")
        (yae-ansi-brightblack   . "#676e95")
        (yae-ansi-brightblue    . "#82aaff")
        (yae-ansi-brightcyan    . "#89ddff")
        (yae-ansi-brightgreen   . "#c3e88d")
        (yae-ansi-brightmagenta . "#c792ea")
        (yae-ansi-brightred     . "#f07178")
        (yae-ansi-brightwhite   . "#ffffff")
        (yae-ansi-brightyellow  . "#ffcb6b")
        (yae-ansi-cyan          . "#89ddff")
        (yae-ansi-green         . "#c3e88d")
        (yae-ansi-magenta       . "#c792ea")
        (yae-ansi-red           . "#f07178")
        (yae-ansi-white         . "#959dcb")
        (yae-ansi-yellow        . "#ffcb6b")))

    (nordic-darker
     . ((yae-ansi-black         . "#2e3440")
        (yae-ansi-brightblack   . "#525d72")

        (yae-ansi-red           . "#e16a70")
        (yae-ansi-brightred     . "#ff8c94")

        (yae-ansi-green         . "#b1d380")
        (yae-ansi-brightgreen   . "#d5f7a3")

        (yae-ansi-yellow        . "#ffcb6b")
        (yae-ansi-brightyellow  . "#ffe399")

        ;; (yae-ansi-blue          . "#7498e4")
        ;; (yae-ansi-brightblue    . "#a5cfff")

        (yae-ansi-blue          . "#678be3")
        (yae-ansi-brightblue    . "#82beff")
        
        (yae-ansi-magenta       . "#ad7fcc")
        (yae-ansi-brightmagenta . "#e1b0ff")

        (yae-ansi-cyan          . "#76bfdc")
        (yae-ansi-brightcyan    . "#b3eaff")

        (yae-ansi-white         . "#848bb4")
        (yae-ansi-brightwhite   . "#d8dee9")

        (yae-foreground         . "#959dcb")
        (yae-background         . "#2e3440")))

    (harmonic-dark
     . ((yae-ansi-black         . "#0B1C2C")
        (yae-ansi-blue          . "#8B56BF")
        (yae-ansi-brightblack   . "#627E99")
        (yae-ansi-brightblue    . "#8B56BF")
        (yae-ansi-brightcyan    . "#568BBF")
        (yae-ansi-brightgreen   . "#56BF8B")
        (yae-ansi-brightmagenta . "#BF568B")
        (yae-ansi-brightred     . "#BF8B56")
        (yae-ansi-brightwhite   . "#F7F9FB")
        (yae-ansi-brightyellow  . "#8BBF56")
        (yae-ansi-cyan          . "#568BBF")
        (yae-ansi-green         . "#56BF8B")
        (yae-ansi-magenta       . "#BF568B")
        (yae-ansi-red           . "#BF8B56")
        (yae-ansi-white         . "#CBD6E2")
        (yae-ansi-yellow        . "#8BBF56")))

    (grayscale-dark
     . ((yae-ansi-black         . "#101010")
        (yae-ansi-blue          . "#686868")
        (yae-ansi-brightblack   . "#4c566a")
        (yae-ansi-brightblue    . "#686868")
        (yae-ansi-brightcyan    . "#868686")
        (yae-ansi-brightgreen   . "#8e8e8e")
        (yae-ansi-brightmagenta . "#747474")
        (yae-ansi-brightred     . "#7c7c7c")
        (yae-ansi-brightwhite   . "#f7f7f7")
        (yae-ansi-brightyellow  . "#a0a0a0")
        (yae-ansi-cyan          . "#868686")
        (yae-ansi-green         . "#8e8e8e")
        (yae-ansi-magenta       . "#747474")
        (yae-ansi-red           . "#7c7c7c")
        (yae-ansi-white         . "#e5e9f0")
        (yae-ansi-yellow        . "#a0a0a0")))

    (brewer
     . ((yae-ansi-black         . "#0c0d0e")
        (yae-ansi-blue          . "#3182bd")
        (yae-ansi-brightblack   . "#737475")
        (yae-ansi-brightblue    . "#3182bd")
        (yae-ansi-brightcyan    . "#80b1d3")
        (yae-ansi-brightgreen   . "#31a354")
        (yae-ansi-brightmagenta . "#756bb1")
        (yae-ansi-brightred     . "#e31a1c")
        (yae-ansi-brightwhite   . "#fcfdfe")
        (yae-ansi-brightyellow  . "#dca060")
        (yae-ansi-cyan          . "#80b1d3")
        (yae-ansi-green         . "#31a354")
        (yae-ansi-magenta       . "#756bb1")
        (yae-ansi-red           . "#e31a1c")
        (yae-ansi-white         . "#b7b8b9")
        (yae-ansi-yellow        . "#dca060")))

    (grayscale-light
     . ((yae-ansi-black         . "#f7f7f7")
        (yae-ansi-blue          . "#686868")
        (yae-ansi-brightblack   . "#ababab")
        (yae-ansi-brightblue    . "#686868")
        (yae-ansi-brightcyan    . "#868686")
        (yae-ansi-brightgreen   . "#8e8e8e")
        (yae-ansi-brightmagenta . "#747474")
        (yae-ansi-brightred     . "#7c7c7c")
        (yae-ansi-brightwhite   . "#101010")
        (yae-ansi-brightyellow  . "#a0a0a0")
        (yae-ansi-cyan          . "#868686")
        (yae-ansi-green         . "#8e8e8e")
        (yae-ansi-magenta       . "#747474")
        (yae-ansi-red           . "#7c7c7c")
        (yae-ansi-white         . "#464646")
        (yae-ansi-yellow        . "#a0a0a0")))

    (nord
     . ((yae-ansi-black         . "#2e3440")
        (yae-ansi-blue          . "#ebcb8b")
        (yae-ansi-brightblack   . "#4c566a")
        (yae-ansi-brightblue    . "#ebcb8b")
        (yae-ansi-brightcyan    . "#d08770")
        (yae-ansi-brightgreen   . "#bf616a")
        (yae-ansi-brightmagenta . "#a3be8c")
        (yae-ansi-brightred     . "#88c0d0")
        (yae-ansi-brightwhite   . "#8fbcbb")
        (yae-ansi-brightyellow  . "#5e81ac")
        (yae-ansi-cyan          . "#d08770")
        (yae-ansi-green         . "#bf616a")
        (yae-ansi-magenta       . "#a3be8c")
        (yae-ansi-red           . "#88c0d0")
        (yae-ansi-white         . "#e5e9f0")
        (yae-ansi-yellow        . "#5e81ac")))

    (solarized-dark
     . ((yae-ansi-black         . "#002b36")
        (yae-ansi-blue          . "#268bd2")
        (yae-ansi-brightblack   . "#657b83")
        (yae-ansi-brightblue    . "#268bd2")
        (yae-ansi-brightcyan    . "#2aa198")
        (yae-ansi-brightgreen   . "#859900")
        (yae-ansi-brightmagenta . "#6c71c4")
        (yae-ansi-brightred     . "#dc322f")
        (yae-ansi-brightwhite   . "#fdf6e3")
        (yae-ansi-brightyellow  . "#b58900")
        (yae-ansi-cyan          . "#2aa198")
        (yae-ansi-green         . "#859900")
        (yae-ansi-magenta       . "#6c71c4")
        (yae-ansi-red           . "#dc322f")
        (yae-ansi-white         . "#93a1a1")
        (yae-ansi-yellow        . "#b58900")))

    (solarized-light
     . ((yae-ansi-black         . "#fdf6e3")
        (yae-ansi-blue          . "#268bd2")
        (yae-ansi-brightblack   . "#839496")
        (yae-ansi-brightblue    . "#268bd2")
        (yae-ansi-brightcyan    . "#2aa198")
        (yae-ansi-brightgreen   . "#859900")
        (yae-ansi-brightmagenta . "#6c71c4")
        (yae-ansi-brightred     . "#dc322f")
        (yae-ansi-brightwhite   . "#002b36")
        (yae-ansi-brightyellow  . "#b58900")
        (yae-ansi-cyan          . "#2aa198")
        (yae-ansi-green         . "#859900")
        (yae-ansi-magenta       . "#6c71c4")
        (yae-ansi-red           . "#dc322f")
        (yae-ansi-white         . "#586e75")
        (yae-ansi-yellow        . "#b58900")))

    (one-dark
     . ((yae-ansi-black        . "#282c34")
        (yae-ansi-red          . "#e06c75")
        (yae-ansi-green        . "#98c379")
        (yae-ansi-yellow       . "#e5c07b")
        (yae-ansi-blue         . "#61afef")
        (yae-ansi-magenta      . "#c678dd")
        (yae-ansi-cyan         . "#56b6c2")
        (yae-ansi-white        . "#abb2bf")
        (yae-ansi-brightblack  . "#545862")
        (yae-ansi-brightred    . "#e06c75")
        (yae-ansi-brightgreen  . "#98c379")
        (yae-ansi-brightyellow . "#e5c07b")
        (yae-ansi-brightblue   . "#61afef")
        (yae-ansi-brightmagenta. "#c678dd")
        (yae-ansi-brightcyan   . "#56b6c2")
        (yae-ansi-brightwhite  . "#c8ccd4")))

    ;; (noone-dark
    ;;  . ((yae-ansi-black         . "#282c34")
    ;;     (yae-ansi-brightblack   . "#7f8494")
    ;;     (yae-ansi-red           . "#e06c75")
    ;;     (yae-ansi-brightred     . "#ff8f97")
    ;;     (yae-ansi-green         . "#98c379")
    ;;     (yae-ansi-brightgreen   . "#c0f2a6")
    ;;     (yae-ansi-yellow        . "#e5c07b")
    ;;     (yae-ansi-brightyellow  . "#fce87f")
    ;;     (yae-ansi-blue          . "#61afef")
    ;;     (yae-ansi-brightblue    . "#9ad1ff")
    ;;     (yae-ansi-magenta       . "#c678dd")
    ;;     (yae-ansi-brightmagenta . "#e0b1ff")
    ;;     (yae-ansi-cyan          . "#56c2c2")
    ;;     (yae-ansi-brightcyan    . "#8ae0f7")
    ;;     (yae-ansi-white         . "#abb2bf")
    ;;     (yae-ansi-brightwhite   . "#f0f4fb")))

    ;; (noone-dark
    ;;  . ((yae-ansi-black        . "#2e3440")
    ;;     (yae-ansi-red          . "#e06c75")
    ;;     (yae-ansi-green        . "#98c379")
    ;;     (yae-ansi-yellow       . "#e5c07b")
    ;;     (yae-ansi-blue         . "#61afef")
    ;;     (yae-ansi-magenta      . "#c678dd")
    ;;     (yae-ansi-cyan         . "#56b6c2")
    ;;     (yae-ansi-white        . "#abb2bf")
    ;;     (yae-ansi-brightblack  . "#4c566a")  ; brighter dark gray
    ;;     (yae-ansi-brightred    . "#ff6c6b")  ; more vivid red
    ;;     (yae-ansi-brightgreen  . "#b4f27b")  ; brighter lime green
    ;;     (yae-ansi-brightyellow . "#f0db6e")  ; brighter yellow
    ;;     (yae-ansi-brightblue   . "#7fc1ff")  ; lighter blue
    ;;     (yae-ansi-brightmagenta. "#d8a9e3")  ; lighter magenta
    ;;     (yae-ansi-brightcyan   . "#63e2e8")  ; brighter cyan
    ;;     (yae-ansi-brightwhite  . "#e6e9ef"))) ; near white

    (noone-dark
     . ((yae-ansi-black        . "#2e3440")
        (yae-ansi-red          . "#e06c75")
        (yae-ansi-green        . "#98c379")
        (yae-ansi-yellow       . "#e5c07b")
        (yae-ansi-blue         . "#61afef")
        (yae-ansi-magenta      . "#c678dd")
        (yae-ansi-cyan         . "#56b6c2")
        (yae-ansi-white        . "#abb2bf")
        (yae-ansi-brightblack  . "#5c667a")  ; was "#4c566a"         ;; Adjusted bright black for better readability: lighter and more contrast
        (yae-ansi-brightred    . "#ff6c6b")
        (yae-ansi-brightgreen  . "#b4f27b")
        (yae-ansi-brightyellow . "#f0db6e")
        (yae-ansi-brightblue   . "#7fc1ff")
        (yae-ansi-brightmagenta. "#d8a9e3")
        (yae-ansi-brightcyan   . "#63e2e8")
        (yae-ansi-brightwhite  . "#d9dce3")))  ; was "#e6e9ef"         ;; Adjusted bright white for better readability: slightly darker and warmer off-white

    (unikitty-dark
     . ((yae-ansi-black        . "#2e2a31")
        (yae-ansi-red          . "#d8137f")
        (yae-ansi-green        . "#17ad98")
        (yae-ansi-yellow       . "#dc8a0e")
        (yae-ansi-blue         . "#796af5")
        (yae-ansi-magenta      . "#bb60ea")
        (yae-ansi-cyan         . "#149bda")
        (yae-ansi-white        . "#bcbabe")
        (yae-ansi-brightblack  . "#838085")
        (yae-ansi-brightred    . "#d8137f")
        (yae-ansi-brightgreen  . "#17ad98")
        (yae-ansi-brightyellow . "#dc8a0e")
        (yae-ansi-brightblue   . "#796af5")
        (yae-ansi-brightmagenta. "#bb60ea")
        (yae-ansi-brightcyan   . "#149bda")
        (yae-ansi-brightwhite  . "#f5f4f7")))

    (unikitty-light
     . ((yae-ansi-black        . "#ffffff")
        (yae-ansi-red          . "#d8137f")
        (yae-ansi-green        . "#17ad98")
        (yae-ansi-yellow       . "#dc8a0e")
        (yae-ansi-blue         . "#775dff")
        (yae-ansi-magenta      . "#aa17e6")
        (yae-ansi-cyan         . "#149bda")
        (yae-ansi-white        . "#6c696e")
        (yae-ansi-brightblack  . "#a7a5a8")
        (yae-ansi-brightred    . "#d8137f")
        (yae-ansi-brightgreen  . "#17ad98")
        (yae-ansi-brightyellow . "#dc8a0e")
        (yae-ansi-brightblue   . "#775dff")
        (yae-ansi-brightmagenta. "#aa17e6")
        (yae-ansi-brightcyan   . "#149bda")
        (yae-ansi-brightwhite  . "#322d34")))

    (dracula
     . ((yae-ansi-black        . "#282936")
        (yae-ansi-red          . "#ea51b2")
        (yae-ansi-green        . "#ebff87")
        (yae-ansi-yellow       . "#00f769")
        (yae-ansi-blue         . "#62d6e8")
        (yae-ansi-magenta      . "#b45bcf")
        (yae-ansi-cyan         . "#a1efe4")
        (yae-ansi-white        . "#e9e9f4")
        (yae-ansi-brightblack  . "#626483")
        (yae-ansi-brightred    . "#ea51b2")
        (yae-ansi-brightgreen  . "#ebff87")
        (yae-ansi-brightyellow . "#00f769")
        (yae-ansi-brightblue   . "#62d6e8")
        (yae-ansi-brightmagenta. "#b45bcf")
        (yae-ansi-brightcyan   . "#a1efe4")
        (yae-ansi-brightwhite  . "#f7f7fb")))

    (monokai
     . ((yae-ansi-black        . "#272822")
        (yae-ansi-red          . "#f92672")
        (yae-ansi-green        . "#a6e22e")
        (yae-ansi-yellow       . "#f4bf75")
        (yae-ansi-blue         . "#66d9ef")
        (yae-ansi-magenta      . "#ae81ff")
        (yae-ansi-cyan         . "#a1efe4")
        (yae-ansi-white        . "#f8f8f2")
        (yae-ansi-brightblack  . "#75715e")
        (yae-ansi-brightred    . "#fd971f")
        (yae-ansi-brightgreen  . "#9bcf34")
        (yae-ansi-brightyellow . "#e6db74")
        (yae-ansi-brightblue   . "#5dade2")
        (yae-ansi-brightmagenta. "#d336d3")
        (yae-ansi-brightcyan   . "#5fd7ff")
        (yae-ansi-brightwhite  . "#f9f9f3")))

    (mariana
     . ((yae-ansi-black        . "#1e1e1e")
        (yae-ansi-red          . "#ff5c57")
        (yae-ansi-green        . "#5af78e")
        (yae-ansi-yellow       . "#f3f99d")
        (yae-ansi-blue         . "#57c7ff")
        (yae-ansi-magenta      . "#ff6ac1")
        (yae-ansi-cyan         . "#9aedfe")
        (yae-ansi-white        . "#e2e2e2")
        (yae-ansi-brightblack  . "#4a4a4a")
        (yae-ansi-brightred    . "#ff5c57")
        (yae-ansi-brightgreen  . "#5af78e")
        (yae-ansi-brightyellow . "#f3f99d")
        (yae-ansi-brightblue   . "#57c7ff")
        (yae-ansi-brightmagenta. "#ff6ac1")
        (yae-ansi-brightcyan   . "#9aedfe")
        (yae-ansi-brightwhite  . "#ffffff")))

    (sixteen
     . ((yae-ansi-black        . "#202020")
        (yae-ansi-red          . "#ff5f5f")
        (yae-ansi-green        . "#87d787")
        (yae-ansi-yellow       . "#d7d787")
        (yae-ansi-blue         . "#5fafd7")
        (yae-ansi-magenta      . "#af87d7")
        (yae-ansi-cyan         . "#5fd7d7")
        (yae-ansi-white        . "#e0e0e0")
        (yae-ansi-brightblack  . "#5f5f5f")
        (yae-ansi-brightred    . "#ff5f5f")
        (yae-ansi-brightgreen  . "#87d787")
        (yae-ansi-brightyellow . "#d7d787")
        (yae-ansi-brightblue   . "#5fafd7")
        (yae-ansi-brightmagenta. "#af87d7")
        (yae-ansi-brightcyan   . "#5fd7d7")
        (yae-ansi-brightwhite  . "#ffffff")))

    (twilight
     . ((yae-ansi-black        . "#141414")
        (yae-ansi-red          . "#cf6a4c")
        (yae-ansi-green        . "#8f9d6a")
        (yae-ansi-yellow       . "#f9ee98")
        (yae-ansi-blue         . "#7587a6")
        (yae-ansi-magenta      . "#9b859d")
        (yae-ansi-cyan         . "#afc4db")
        (yae-ansi-white        . "#c3c3c3")
        (yae-ansi-brightblack  . "#5f5a60")
        (yae-ansi-brightred    . "#cf6a4c")
        (yae-ansi-brightgreen  . "#8f9d6a")
        (yae-ansi-brightyellow . "#f9ee98")
        (yae-ansi-brightblue   . "#7587a6")
        (yae-ansi-brightmagenta. "#9b859d")
        (yae-ansi-brightcyan   . "#afc4db")
        (yae-ansi-brightwhite  . "#ffffff")))

    (one-dark
     . ((yae-ansi-black        . "#282c34")
        (yae-ansi-red          . "#e06c75")
        (yae-ansi-green        . "#98c379")
        (yae-ansi-yellow       . "#e5c07b")
        (yae-ansi-blue         . "#61afef")
        (yae-ansi-magenta      . "#c678dd")
        (yae-ansi-cyan         . "#56b6c2")
        (yae-ansi-white        . "#abb2bf")
        (yae-ansi-brightblack  . "#353b45")
        (yae-ansi-brightred    . "#e06c75")
        (yae-ansi-brightgreen  . "#98c379")
        (yae-ansi-brightyellow . "#e5c07b")
        (yae-ansi-brightblue   . "#61afef")
        (yae-ansi-brightmagenta. "#c678dd")
        (yae-ansi-brightcyan   . "#56b6c2")
        (yae-ansi-brightwhite  . "#c8ccd4")))


    (vscode-dark+
     . ((yae-ansi-black        . "#1e1e1e")
        (yae-ansi-red          . "#f44747")
        (yae-ansi-green        . "#608b4e")
        (yae-ansi-yellow       . "#dcdcaa")
        (yae-ansi-blue         . "#569cd6")
        (yae-ansi-magenta      . "#c586c0")
        (yae-ansi-cyan         . "#9cdcfe")
        (yae-ansi-white        . "#d4d4d4")
        (yae-ansi-brightblack  . "#3e3e42")
        (yae-ansi-brightred    . "#d16969")
        (yae-ansi-brightgreen  . "#b5cea8")
        (yae-ansi-brightyellow . "#ce9178")
        (yae-ansi-brightblue   . "#4fc1ff")
        (yae-ansi-brightmagenta. "#c586c0")
        (yae-ansi-brightcyan   . "#4ec9b0")
        (yae-ansi-brightwhite  . "#ffffff")))

    (doom-one
     . ((yae-ansi-black        . "#282c34")
        (yae-ansi-red          . "#ff6c6b")
        (yae-ansi-green        . "#98be65")
        (yae-ansi-yellow       . "#da8548")
        (yae-ansi-blue         . "#51afef")
        (yae-ansi-magenta      . "#c678dd")
        (yae-ansi-cyan         . "#5699af")
        (yae-ansi-white        . "#bbc2cf")
        (yae-ansi-brightblack  . "#5b6268")
        (yae-ansi-brightred    . "#ff6655")
        (yae-ansi-brightgreen  . "#99bb66")
        (yae-ansi-brightyellow . "#ecbe7b")
        (yae-ansi-brightblue   . "#61afef")
        (yae-ansi-brightmagenta. "#c678dd")
        (yae-ansi-brightcyan   . "#46d9ff")
        (yae-ansi-brightwhite  . "#dfdfdf")))

    (doom-dracula
     . ((yae-ansi-black        . "#282a36")
        (yae-ansi-red          . "#ff5555")
        (yae-ansi-green        . "#50fa7b")
        (yae-ansi-yellow       . "#f1fa8c")
        (yae-ansi-blue         . "#bd93f9")
        (yae-ansi-magenta      . "#ff79c6")
        (yae-ansi-cyan         . "#8be9fd")
        (yae-ansi-white        . "#f8f8f2")
        (yae-ansi-brightblack  . "#6272a4")
        (yae-ansi-brightred    . "#ff6e6e")
        (yae-ansi-brightgreen  . "#69ff94")
        (yae-ansi-brightyellow . "#ffffa5")
        (yae-ansi-brightblue   . "#d6acff")
        (yae-ansi-brightmagenta. "#ff92df")
        (yae-ansi-brightcyan   . "#a4ffff")
        (yae-ansi-brightwhite  . "#ffffff")))

    (doom-nord
     . ((yae-ansi-black        . "#2e3440")
        (yae-ansi-red          . "#bf616a")
        (yae-ansi-green        . "#a3be8c")
        (yae-ansi-yellow       . "#ebcb8b")
        (yae-ansi-blue         . "#81a1c1")
        (yae-ansi-magenta      . "#b48ead")
        (yae-ansi-cyan         . "#88c0d0")
        (yae-ansi-white        . "#e5e9f0")
        (yae-ansi-brightblack  . "#4c566a")
        (yae-ansi-brightred    . "#d08770")
        (yae-ansi-brightgreen  . "#8fbcbb")
        (yae-ansi-brightyellow . "#eac785")
        (yae-ansi-brightblue   . "#5e81ac")
        (yae-ansi-brightmagenta. "#b48ead")
        (yae-ansi-brightcyan   . "#8fbcbb")
        (yae-ansi-brightwhite  . "#eceff4")))

    (doom-gruvbox
     . ((yae-ansi-black        . "#282828")
        (yae-ansi-red          . "#cc241d")
        (yae-ansi-green        . "#98971a")
        (yae-ansi-yellow       . "#d79921")
        (yae-ansi-blue         . "#458588")
        (yae-ansi-magenta      . "#b16286")
        (yae-ansi-cyan         . "#689d6a")
        (yae-ansi-white        . "#a89984")
        (yae-ansi-brightblack  . "#928374")
        (yae-ansi-brightred    . "#fb4934")
        (yae-ansi-brightgreen  . "#b8bb26")
        (yae-ansi-brightyellow . "#fabd2f")
        (yae-ansi-brightblue   . "#83a598")
        (yae-ansi-brightmagenta. "#d3869b")
        (yae-ansi-brightcyan   . "#8ec07c")
        (yae-ansi-brightwhite  . "#ebdbb2")))

    (doom-tomorrow-night
     . ((yae-ansi-black        . "#1d1f21")
        (yae-ansi-red          . "#cc6666")
        (yae-ansi-green        . "#b5bd68")
        (yae-ansi-yellow       . "#f0c674")
        (yae-ansi-blue         . "#81a2be")
        (yae-ansi-magenta      . "#b294bb")
        (yae-ansi-cyan         . "#8abeb7")
        (yae-ansi-white        . "#c5c8c6")
        (yae-ansi-brightblack  . "#666666")
        (yae-ansi-brightred    . "#d54e53")
        (yae-ansi-brightgreen  . "#b9ca4a")
        (yae-ansi-brightyellow . "#e7c547")
        (yae-ansi-brightblue   . "#7aa6da")
        (yae-ansi-brightmagenta. "#c397d8")
        (yae-ansi-brightcyan   . "#70c0b1")
        (yae-ansi-brightwhite  . "#eaeaea")))

    (doom-iosvkem
     . ((yae-ansi-black        . "#262626")
        (yae-ansi-red          . "#ff005f")
        (yae-ansi-green        . "#afd700")
        (yae-ansi-yellow       . "#ffaf00")
        (yae-ansi-blue         . "#0087ff")
        (yae-ansi-magenta      . "#af87ff")
        (yae-ansi-cyan         . "#00afaf")
        (yae-ansi-white        . "#bcbcbc")
        (yae-ansi-brightblack  . "#4e4e4e")
        (yae-ansi-brightred    . "#ff5f87")
        (yae-ansi-brightgreen  . "#d7ff00")
        (yae-ansi-brightyellow . "#ffd700")
        (yae-ansi-brightblue   . "#5fafff")
        (yae-ansi-brightmagenta. "#d7afff")
        (yae-ansi-brightcyan   . "#00d7d7")
        (yae-ansi-brightwhite  . "#ffffff")))

    (doom-acario-dark
     . ((yae-ansi-black        . "#1a1a1a")
        (yae-ansi-red          . "#ff6b6b")
        (yae-ansi-green        . "#a8ce93")
        (yae-ansi-yellow       . "#f1c27d")
        (yae-ansi-blue         . "#7aa2f7")
        (yae-ansi-magenta      . "#bb9af7")
        (yae-ansi-cyan         . "#7dcfff")
        (yae-ansi-white        . "#c0caf5")
        (yae-ansi-brightblack  . "#414868")
        (yae-ansi-brightred    . "#f7768e")
        (yae-ansi-brightgreen  . "#9ece6a")
        (yae-ansi-brightyellow . "#e0af68")
        (yae-ansi-brightblue   . "#7aa2f7")
        (yae-ansi-brightmagenta. "#bb9af7")
        (yae-ansi-brightcyan   . "#7dcfff")
        (yae-ansi-brightwhite  . "#ffffff")))

    (doom-challenger-deep
     . ((yae-ansi-black        . "#1e1c31")
        (yae-ansi-red          . "#ff5458")
        (yae-ansi-green        . "#62d196")
        (yae-ansi-yellow       . "#ffb378")
        (yae-ansi-blue         . "#65b2ff")
        (yae-ansi-magenta      . "#906cff")
        (yae-ansi-cyan         . "#63f2f1")
        (yae-ansi-white        . "#a6b3cc")
        (yae-ansi-brightblack  . "#565575")
        (yae-ansi-brightred    . "#ff8080")
        (yae-ansi-brightgreen  . "#95ffa4")
        (yae-ansi-brightyellow . "#ffe9aa")
        (yae-ansi-brightblue   . "#91ddff")
        (yae-ansi-brightmagenta. "#c991e1")
        (yae-ansi-brightcyan   . "#aaffe4")
        (yae-ansi-brightwhite  . "#cbe3e7")))

    (doom-city-lights
     . ((yae-ansi-black        . "#1d252c")
        (yae-ansi-red          . "#ff5874")
        (yae-ansi-green        . "#5fffaf")
        (yae-ansi-yellow       . "#ecc48d")
        (yae-ansi-blue         . "#5ca7e4")
        (yae-ansi-magenta      . "#ff9ac1")
        (yae-ansi-cyan         . "#7fdbca")
        (yae-ansi-white        . "#718ca1")
        (yae-ansi-brightblack  . "#334e68")
        (yae-ansi-brightred    . "#ff869a")
        (yae-ansi-brightgreen  . "#9effd1")
        (yae-ansi-brightyellow . "#f0c989")
        (yae-ansi-brightblue   . "#82aaff")
        (yae-ansi-brightmagenta. "#ffb3d7")
        (yae-ansi-brightcyan   . "#a1ffff")
        (yae-ansi-brightwhite  . "#d6deeb")))

    (doom-laserwave
     . ((yae-ansi-black        . "#1a1a2a")
        (yae-ansi-red          . "#f02e6e")
        (yae-ansi-green        . "#72f1b8")
        (yae-ansi-yellow       . "#f8f8b8")
        (yae-ansi-blue         . "#7e6bc4")
        (yae-ansi-magenta      . "#c792ea")
        (yae-ansi-cyan         . "#00e8c6")
        (yae-ansi-white        . "#b8c5db")
        (yae-ansi-brightblack  . "#353154")
        (yae-ansi-brightred    . "#ff7eb6")
        (yae-ansi-brightgreen  . "#a1f7b5")
        (yae-ansi-brightyellow . "#fefeca")
        (yae-ansi-brightblue   . "#a4a8ff")
        (yae-ansi-brightmagenta. "#e1a6ff")
        (yae-ansi-brightcyan   . "#5af7b5")
        (yae-ansi-brightwhite  . "#ffffff")))

    (doom-molokai
     . ((yae-ansi-black        . "#1e1e1e")
        (yae-ansi-red          . "#f92672")
        (yae-ansi-green        . "#a6e22e")
        (yae-ansi-yellow       . "#e6db74")
        (yae-ansi-blue         . "#66d9ef")
        (yae-ansi-magenta      . "#ae81ff")
        (yae-ansi-cyan         . "#a1efe4")
        (yae-ansi-white        . "#f8f8f2")
        (yae-ansi-brightblack  . "#75715e")
        (yae-ansi-brightred    . "#fd971f")
        (yae-ansi-brightgreen  . "#9bcf34")
        (yae-ansi-brightyellow . "#e6db74")
        (yae-ansi-brightblue   . "#5dade2")
        (yae-ansi-brightmagenta. "#d336d3")
        (yae-ansi-brightcyan   . "#5fd7ff")
        (yae-ansi-brightwhite  . "#f9f9f3")))

    (doom-tokyo-night
     . ((yae-ansi-black        . "#1a1b26")
        (yae-ansi-red          . "#f7768e")
        (yae-ansi-green        . "#9ece6a")
        (yae-ansi-yellow       . "#e0af68")
        (yae-ansi-blue         . "#7aa2f7")
        (yae-ansi-magenta      . "#bb9af7")
        (yae-ansi-cyan         . "#7dcfff")
        (yae-ansi-white        . "#c0caf5")
        (yae-ansi-brightblack  . "#414868")
        (yae-ansi-brightred    . "#ff7a93")
        (yae-ansi-brightgreen  . "#b9f27c")
        (yae-ansi-brightyellow . "#ff9e64")
        (yae-ansi-brightblue   . "#7da6ff")
        (yae-ansi-brightmagenta. "#c0a7f2")
        (yae-ansi-brightcyan   . "#a2d8ff")
        (yae-ansi-brightwhite  . "#ffffff")))

    (doom-zenburn
     . ((yae-ansi-black        . "#3f3f3f")
        (yae-ansi-red          . "#cc9393")
        (yae-ansi-green        . "#7f9f7f")
        (yae-ansi-yellow       . "#f0dfaf")
        (yae-ansi-blue         . "#8cd0d3")
        (yae-ansi-magenta      . "#dc8cc3")
        (yae-ansi-cyan         . "#93e0e3")
        (yae-ansi-white        . "#dcdccc")
        (yae-ansi-brightblack  . "#709080")
        (yae-ansi-brightred    . "#dca3a3")
        (yae-ansi-brightgreen  . "#9faf8f")
        (yae-ansi-brightyellow . "#e0cf9f")
        (yae-ansi-brightblue   . "#94bff3")
        (yae-ansi-brightmagenta. "#ec93d3")
        (yae-ansi-brightcyan   . "#9ce0e3")
        (yae-ansi-brightwhite  . "#ffffff")))

    ;; (spacemacs-dark
    ;;  . ((yae-ansi-black        . "#1f2022")
    ;;     (yae-ansi-red          . "#f2241f")
    ;;     (yae-ansi-green        . "#67b11d")
    ;;     (yae-ansi-yellow       . "#b1951d")
    ;;     (yae-ansi-blue         . "#4f97d7")
    ;;     (yae-ansi-magenta      . "#a31db1")
    ;;     (yae-ansi-cyan         . "#2d9574")
    ;;     (yae-ansi-white        . "#a3a3a3")
    ;;     (yae-ansi-brightblack  . "#585858")
    ;;     (yae-ansi-brightred    . "#ff5d62")
    ;;     (yae-ansi-brightgreen  . "#86dc2f")
    ;;     (yae-ansi-brightyellow . "#e5d11c")
    ;;     (yae-ansi-brightblue   . "#5ca7e4")
    ;;     (yae-ansi-brightmagenta. "#d337d3")
    ;;     (yae-ansi-brightcyan   . "#2cd1d1")
    ;;     (yae-ansi-brightwhite  . "#f8f8f2")))

    (spacemacs-dark
     . ((yae-ansi-black        . "#292b2e")
        (yae-ansi-red          . "#f2241f")
        (yae-ansi-green        . "#67b11d")
        (yae-ansi-yellow       . "#b1951d")
        (yae-ansi-blue         . "#4f97d7")
        (yae-ansi-magenta      . "#a31db1")
        (yae-ansi-cyan         . "#28def0")
        (yae-ansi-white        . "#b2b2b2")
        (yae-ansi-brightblack  . "#686868")
        (yae-ansi-brightred    . "#e0211d")
        (yae-ansi-brightgreen  . "#86dc2f")
        (yae-ansi-brightyellow . "#dc752f")
        (yae-ansi-brightblue   . "#5d77a3")
        (yae-ansi-brightmagenta. "#c56ec3")
        (yae-ansi-brightcyan   . "#2aa1ae")
        (yae-ansi-brightwhite  . "#f8f8f2")))

    (spacemacs-light
     . ((yae-ansi-black        . "#fbf8ef")
        (yae-ansi-red          . "#f2241f")
        (yae-ansi-green        . "#67b11d")
        (yae-ansi-yellow       . "#b1951d")
        (yae-ansi-blue         . "#3a81c3")
        (yae-ansi-magenta      . "#a31db1")
        (yae-ansi-cyan         . "#21b8c7")
        (yae-ansi-white        . "#655370")
        (yae-ansi-brightblack  . "#a094a2")
        (yae-ansi-brightred    . "#e0211d")
        (yae-ansi-brightgreen  . "#42ae2c")
        (yae-ansi-brightyellow . "#dc752f")
        (yae-ansi-brightblue   . "#715ab1")
        (yae-ansi-brightmagenta. "#6c4173")
        (yae-ansi-brightcyan   . "#2aa1ae")
        (yae-ansi-brightwhite  . "#100a14")))

    (atelier-dune
     . ((yae-ansi-black        . "#20201d")
        (yae-ansi-red          . "#d73737")
        (yae-ansi-green        . "#60ac39")
        (yae-ansi-yellow       . "#ae9513")
        (yae-ansi-blue         . "#6684e1")
        (yae-ansi-magenta      . "#b854d4")
        (yae-ansi-cyan         . "#1fad83")
        (yae-ansi-white        . "#a6a28c")
        (yae-ansi-brightblack  . "#7d7a68")
        (yae-ansi-brightred    . "#d73737")
        (yae-ansi-brightgreen  . "#60ac39")
        (yae-ansi-brightyellow . "#ae9513")
        (yae-ansi-brightblue   . "#6684e1")678be3
        (yae-ansi-brightmagenta. "#b854d4")
        (yae-ansi-brightcyan   . "#1fad83")
        (yae-ansi-brightwhite  . "#fefbec")))

    (atelier-forest
     . ((yae-ansi-black        . "#1b1918")
        (yae-ansi-red          . "#f22c40")
        (yae-ansi-green        . "#7b9726")
        (yae-ansi-yellow       . "#c38418")
        (yae-ansi-blue         . "#407ee7")
        (yae-ansi-magenta      . "#6666ea")
        (yae-ansi-cyan         . "#3d97b8")
        (yae-ansi-white        . "#a8a19f")
        (yae-ansi-brightblack  . "#766e6b")
        (yae-ansi-brightred    . "#f22c40")
        (yae-ansi-brightgreen  . "#7b9726")
        (yae-ansi-brightyellow . "#c38418")
        (yae-ansi-brightblue   . "#407ee7")
        (yae-ansi-brightmagenta. "#6666ea")
        (yae-ansi-brightcyan   . "#3d97b8")
        (yae-ansi-brightwhite  . "#f1efee")))

    (atelier-heath
     . ((yae-ansi-black        . "#1b181b")
        (yae-ansi-red          . "#ca402b")
        (yae-ansi-green        . "#918b3b")
        (yae-ansi-yellow       . "#bb8a35")
        (yae-ansi-blue         . "#516aec")
        (yae-ansi-magenta      . "#7b59c0")
        (yae-ansi-cyan         . "#159393")
        (yae-ansi-white        . "#ab9bab")
        (yae-ansi-brightblack  . "#776977")
        (yae-ansi-brightred    . "#ca402b")
        (yae-ansi-brightgreen  . "#918b3b")
        (yae-ansi-brightyellow . "#bb8a35")
        (yae-ansi-brightblue   . "#516aec")
        (yae-ansi-brightmagenta. "#7b59c0")
        (yae-ansi-brightcyan   . "#159393")
        (yae-ansi-brightwhite  . "#f7f3f7")))

    (atelier-lakeside
     . ((yae-ansi-black        . "#161b1d")
        (yae-ansi-red          . "#d22d72")
        (yae-ansi-green        . "#568c3b")
        (yae-ansi-yellow       . "#8a8a0f")
        (yae-ansi-blue         . "#257fad")
        (yae-ansi-magenta      . "#6b6bb8")
        (yae-ansi-cyan         . "#2d8f6f")
        (yae-ansi-white        . "#7ea2b4")
        (yae-ansi-brightblack  . "#5a7b8c")
        (yae-ansi-brightred    . "#d22d72")
        (yae-ansi-brightgreen  . "#568c3b")
        (yae-ansi-brightyellow . "#8a8a0f")
        (yae-ansi-brightblue   . "#257fad")
        (yae-ansi-brightmagenta. "#6b6bb8")
        (yae-ansi-brightcyan   . "#2d8f6f")
        (yae-ansi-brightwhite  . "#ebf8ff")))

    (atelier-seaside
     . ((yae-ansi-black        . "#131513")
        (yae-ansi-red          . "#e6193c")
        (yae-ansi-green        . "#29a329")
        (yae-ansi-yellow       . "#98981b")
        (yae-ansi-blue         . "#3d62f5")
        (yae-ansi-magenta      . "#ad2bee")
        (yae-ansi-cyan         . "#1999b3")
        (yae-ansi-white        . "#8ca68c")
        (yae-ansi-brightblack  . "#687d68")
        (yae-ansi-brightred    . "#e6193c")
        (yae-ansi-brightgreen  . "#29a329")
        (yae-ansi-brightyellow . "#98981b")
        (yae-ansi-brightblue   . "#3d62f5")
        (yae-ansi-brightmagenta. "#ad2bee")
        (yae-ansi-brightcyan   . "#1999b3")
        (yae-ansi-brightwhite  . "#f4fbf4")))

    (atelier-sulphurpool
     . ((yae-ansi-black        . "#202746")
        (yae-ansi-red          . "#c94922")
        (yae-ansi-green        . "#ac9739")
        (yae-ansi-yellow       . "#c08b30")
        (yae-ansi-blue         . "#3d8fd1")
        (yae-ansi-magenta      . "#6679cc")
        (yae-ansi-cyan         . "#22a2c9")
        (yae-ansi-white        . "#979db4")
        (yae-ansi-brightblack  . "#6b7394")
        (yae-ansi-brightred    . "#c94922")
        (yae-ansi-brightgreen  . "#ac9739")
        (yae-ansi-brightyellow . "#c08b30")
        (yae-ansi-brightblue   . "#3d8fd1")
        (yae-ansi-brightmagenta. "#6679cc")
        (yae-ansi-brightcyan   . "#22a2c9")
        (yae-ansi-brightwhite  . "#f5f7ff")))

    (github-dark
     . ((yae-ansi-black        . "#0d1117")
        (yae-ansi-red          . "#ff7b72")
        (yae-ansi-green        . "#7ee787")
        (yae-ansi-yellow       . "#f2cc60")
        (yae-ansi-blue         . "#79c0ff")
        (yae-ansi-magenta      . "#d2a8ff")
        (yae-ansi-cyan         . "#a5d6ff")
        (yae-ansi-white        . "#c9d1d9")
        (yae-ansi-brightblack  . "#484f58")
        (yae-ansi-brightred    . "#ffa198")
        (yae-ansi-brightgreen  . "#56d364")
        (yae-ansi-brightyellow . "#e3b341")
        (yae-ansi-brightblue   . "#58a6ff")
        (yae-ansi-brightmagenta. "#bc8cff")
        (yae-ansi-brightcyan   . "#56d4dd")
        (yae-ansi-brightwhite  . "#f0f6fc")))


    (github-light
     . ((yae-ansi-black        . "#ffffff")
        (yae-ansi-red          . "#d73a49")
        (yae-ansi-green        . "#28a745")
        (yae-ansi-yellow       . "#dbab09")
        (yae-ansi-blue         . "#0366d6")
        (yae-ansi-magenta      . "#5a32a3")
        (yae-ansi-cyan         . "#0598bc")
        (yae-ansi-white        . "#24292e")
        (yae-ansi-brightblack  . "#e1e4e8")
        (yae-ansi-brightred    . "#cb2431")
        (yae-ansi-brightgreen  . "#22863a")
        (yae-ansi-brightyellow . "#b08800")
        (yae-ansi-brightblue   . "#005cc5")
        (yae-ansi-brightmagenta. "#4f2a9a")
        (yae-ansi-brightcyan   . "#0086b3")
        (yae-ansi-brightwhite  . "#1b1f23")))

    (one-light
     . ((yae-ansi-black        . "#fafafa")
        (yae-ansi-red          . "#e45649")
        (yae-ansi-green        . "#50a14f")
        (yae-ansi-yellow       . "#c18401")
        (yae-ansi-blue         . "#4078f2")
        (yae-ansi-magenta      . "#a626a4")
        (yae-ansi-cyan         . "#0184bc")
        (yae-ansi-white        . "#383a42")
        (yae-ansi-brightblack  . "#e5e5e6")
        (yae-ansi-brightred    . "#ca1243")
        (yae-ansi-brightgreen  . "#86b300")
        (yae-ansi-brightyellow . "#f2a60d")
        (yae-ansi-brightblue   . "#3a5bcd")
        (yae-ansi-brightmagenta. "#9b2393")
        (yae-ansi-brightcyan   . "#0098dd")
        (yae-ansi-brightwhite  . "#202227")))

    (gruvbox-light
     . ((yae-ansi-black        . "#fbf1c7")   ; Background
        (yae-ansi-red          . "#cc241d")   ; Errors
        (yae-ansi-green        . "#98971a")   ; Strings
        (yae-ansi-yellow       . "#d79921")   ; Keywords
        (yae-ansi-blue         . "#458588")   ; Functions
        (yae-ansi-magenta      . "#b16286")   ; Special
        (yae-ansi-cyan         . "#689d6a")   ; Tags
        (yae-ansi-white        . "#3c3836")   ; Foreground
        (yae-ansi-brightblack  . "#ebdbb2")   ; Comments
        (yae-ansi-brightred    . "#9d0006")   ; Strong errors
        (yae-ansi-brightgreen  . "#79740e")   ; Strong strings
        (yae-ansi-brightyellow . "#b57614")   ; Strong keywords
        (yae-ansi-brightblue   . "#076678")   ; Strong functions
        (yae-ansi-brightmagenta. "#8f3f71")   ; Strong special
        (yae-ansi-brightcyan   . "#427b58")   ; Strong tags
        (yae-ansi-brightwhite  . "#282828"))) ; Bold text

    (papercolor-light
     . ((yae-ansi-black        . "#eeeeee")
        (yae-ansi-red          . "#af0000")
        (yae-ansi-green        . "#008700")
        (yae-ansi-yellow       . "#5f8700")
        (yae-ansi-blue         . "#0087af")
        (yae-ansi-magenta      . "#878787")
        (yae-ansi-cyan         . "#005f87")
        (yae-ansi-white        . "#444444")
        (yae-ansi-brightblack  . "#bcbcbc")
        (yae-ansi-brightred    . "#d70000")
        (yae-ansi-brightgreen  . "#d70087")
        (yae-ansi-brightyellow . "#8700af")
        (yae-ansi-brightblue   . "#d75f00")
        (yae-ansi-brightmagenta. "#d75f00")
        (yae-ansi-brightcyan   . "#005faf")
        (yae-ansi-brightwhite  . "#005f87")))

    (ayu-dark
     . ((yae-ansi-black        . "#0a0e14")
        (yae-ansi-red          . "#ff3333")
        (yae-ansi-green        . "#b8cc52")
        (yae-ansi-yellow       . "#e6c446")
        (yae-ansi-blue         . "#36a3d9")
        (yae-ansi-magenta      . "#f07078")
        (yae-ansi-cyan         . "#95e6cb")
        (yae-ansi-white        . "#e6e1cf")
        (yae-ansi-brightblack  . "#4d5566")
        (yae-ansi-brightred    . "#ff6565")
        (yae-ansi-brightgreen  . "#d2e865")
        (yae-ansi-brightyellow . "#ffe14d")
        (yae-ansi-brightblue   . "#68d4ff")
        (yae-ansi-brightmagenta. "#ff8f8f")
        (yae-ansi-brightcyan   . "#a8ffdb")
        (yae-ansi-brightwhite  . "#f8f8f0")))

    (ayu-light
     . ((yae-ansi-black        . "#fafafa")
        (yae-ansi-red          . "#ff3333")
        (yae-ansi-green        . "#86b300")
        (yae-ansi-yellow       . "#f29718")
        (yae-ansi-blue         . "#41a6d9")
        (yae-ansi-magenta      . "#f07178")
        (yae-ansi-cyan         . "#4dbf99")
        (yae-ansi-white        . "#5c6773")
        (yae-ansi-brightblack  . "#e6e1cf")
        (yae-ansi-brightred    . "#ff6565")
        (yae-ansi-brightgreen  . "#b8cc52")
        (yae-ansi-brightyellow . "#ffb454")
        (yae-ansi-brightblue   . "#68d4ff")
        (yae-ansi-brightmagenta. "#ff8f8f")
        (yae-ansi-brightcyan   . "#a8ffdb")
        (yae-ansi-brightwhite  . "#8a9199")))

    )
  "List of color palettes for themes."
  :type '(alist :key-type symbol :value-type (repeat color))
  :group 'yae-simple-theme)

(defcustom yae-selected-palette 'palenight
  "The currently selected color palette."
  :type 'symbol
  :group 'yae-simple-theme)

(deftheme yae_simple
  "Adopted simple form of base16-themes for personal use"
)

(let* ((color-cells (display-color-cells)) ; Get the number of available colors
       ;; Retrieve the colors associated with the selected palette
       (colors (cdr (assoc yae-selected-palette yae-color-palettes)))

       (yae_simple/base00 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-black colors))
                            "black"))
       (yae_simple/base01 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightgreen colors)) 
                            "brightgreen"))
       (yae_simple/base02 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightyellow colors)) 
                            "brightyellow"))
       (yae_simple/base03 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightblack colors)) 
                            "brightblack"))
       (yae_simple/base04 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightblue colors)) 
                            "brightblue"))
       (yae_simple/base05 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-white colors)) 
                            "white"))
       (yae_simple/base06 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightmagenta colors)) 
                            "brightmagenta"))
       (yae_simple/base07 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightwhite colors)) 
                            "brightwhite"))
       (yae_simple/base08 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-red colors)) 
                            "red"))
       (yae_simple/base09 (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightred colors)) 
                            "brightred"))
       (yae_simple/base0A (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-yellow colors)) 
                            "yellow"))
       (yae_simple/base0B (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-green colors)) 
                            "green"))
       (yae_simple/base0C (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-cyan colors)) 
                            "cyan"))
       (yae_simple/base0D (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-blue colors)) 
                            "blue"))
       (yae_simple/base0E (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-magenta colors)) 
                            "magenta"))
       (yae_simple/base0F (if (and colors (> color-cells 256)) 
                              (cdr (assoc 'yae-ansi-brightcyan colors)) 
                            "brightcyan"))
       )

  (custom-theme-set-faces
   'yae_simple
   `(bold                         ((t (:bold t))))
   `(bold-italic                  ((t (:bold t))))
   `(border-glyph                 ((t (nil))))
   `(buffers-tab                  ((t (:foreground ,yae_simple/base05 :background ,yae_simple/base00))))
   ;; `(mode-line                    ((t (:foreground ,yae_simple/base07 :background ,yae_simple/base01 :box nil))))
   ;; `(mode-line-highlight          ((t (:foreground ,yae_simple/base08 :box nil))))
   `(hl-line                      ((t (:background ,yae_simple/base02))))     ;; Highlight line background 
   ;; `(region                       ((t (:background ,yae_simple/base02))))     ;; Selection region color 
   ;; `(italic                       ((t (nil))))
   `(left-margin                  ((t (nil))))
   `(toolbar                      ((t (nil))))
   ;; `(underline                    ((nil (:underline nil))))))

;;;; basic colors
     `(border                                       ((t (:background ,yae_simple/base03))))
     `(cursor                                       ((t (:background ,yae_simple/base08))))
     `(default                                      ((t (:foreground ,yae_simple/base05 :background ,yae_simple/base00))))
     ;; `(fringe                                       ((t (:background ,yae_simple/base16-settings-fringe-bg))))
     `(fringe                       ((t (:background ,yae_simple/base00))))
     `(gui-element                                  ((t (:background ,yae_simple/base01))))
     `(header-line                                  ((t (:inherit default))))
     `(highlight                                    ((t (:background ,yae_simple/base00))))
     `(link                                         ((t (:foreground ,yae_simple/base0D :underline t))))
     `(link-visited                                 ((t (:foreground ,yae_simple/base0E :underline t))))
     `(minibuffer-prompt                            ((t (:foreground ,yae_simple/base0D))))
     ;; `(region                                       ((t (:background ,yae_simple/base03 :distant-foreground ,yae_simple/base05))))
     `(region
       ((((class color) (min-colors 257))
         (:background ,yae_simple/base03 :distant-foreground ,yae_simple/base05))
        (((class color) (min-colors 256))
         (:background ,yae_simple/base03 :foreground ,yae_simple/base05))))

     `(secondary-selection                          ((t (:inherit 'default :distant-foreground ,yae_simple/base05 :inverse-video t))))
     ;; `(trailing-whitespace                          ((t (:foreground ,yae_simple/base0A :background ,yae_simple/base0C))))
     `(vertical-border                              ((t (:foreground ,yae_simple/base02))))
     `(widget-button                                ((t (:underline t))))
     `(widget-field                                 ((t (:background ,yae_simple/base03 :box (:line-width 1 :color ,yae_simple/base06)))))

     `(error                                        ((t (:foreground ,yae_simple/base08 :weight bold))))
     `(warning                                      ((t (:foreground ,yae_simple/base09 :weight bold))))
     `(success                                      ((t (:foreground ,yae_simple/base0B :weight bold))))
     `(shadow                                       ((t (:foreground ,yae_simple/base03))))
   
;;;; font-lock
     `(font-lock-builtin-face                       ((t (:foreground ,yae_simple/base0C))))
     `(font-lock-comment-delimiter-face             ((t (:foreground ,yae_simple/base03))))
     `(font-lock-comment-face                       ((t (:foreground ,yae_simple/base03 :italic t))))
     `(font-lock-constant-face                      ((t (:foreground ,yae_simple/base09))))
     `(font-lock-doc-face                           ((t (:foreground ,yae_simple/base04))))
     `(font-lock-doc-string-face                    ((t (:foreground ,yae_simple/base03))))
     `(font-lock-function-name-face                 ((t (:foreground ,yae_simple/base0D))))
     `(font-lock-keyword-face                       ((t (:foreground ,yae_simple/base0E))))
     `(font-lock-negation-char-face                 ((t (:foreground ,yae_simple/base0B))))
     `(font-lock-preprocessor-face                  ((t (:foreground ,yae_simple/base0D))))
     `(font-lock-regexp-grouping-backslash          ((t (:foreground ,yae_simple/base0A))))
     `(font-lock-regexp-grouping-construct          ((t (:foreground ,yae_simple/base0E))))
     `(font-lock-string-face                        ((t (:foreground ,yae_simple/base0B))))
     `(font-lock-type-face                          ((t (:foreground ,yae_simple/base0A))))
     `(font-lock-variable-name-face                 ((t (:foreground ,yae_simple/base08))))
     `(font-lock-warning-face                       ((t (:foreground ,yae_simple/base08))))

;;;; ansi-colors
     `(ansi-color-black                             ((t (:foreground ,yae_simple/base00 :background ,yae_simple/base00))))
     `(ansi-color-red                               ((t (:foreground ,yae_simple/base08 :background ,yae_simple/base08))))
     `(ansi-color-green                             ((t (:foreground ,yae_simple/base0B :background ,yae_simple/base0B))))
     `(ansi-color-yellow                            ((t (:foreground ,yae_simple/base0A :background ,yae_simple/base0A))))
     `(ansi-color-blue                              ((t (:foreground ,yae_simple/base0D :background ,yae_simple/base0D))))
     `(ansi-color-magenta                           ((t (:foreground ,yae_simple/base0E :background ,yae_simple/base0E))))
     `(ansi-color-cyan                              ((t (:foreground ,yae_simple/base0C :background ,yae_simple/base0C))))
     `(ansi-color-white                             ((t (:foreground ,yae_simple/base05 :background ,yae_simple/base05))))
                                                   
     `(ansi-color-bright-black                       ((t (:foreground ,yae_simple/base03 :background ,yae_simple/base03))))
     `(ansi-color-bright-red                         ((t (:foreground ,yae_simple/base09 :background ,yae_simple/base09))))
     `(ansi-color-bright-green                       ((t (:foreground ,yae_simple/base01 :background ,yae_simple/base01))))
     `(ansi-color-bright-yellow                      ((t (:foreground ,yae_simple/base02 :background ,yae_simple/base02))))
     `(ansi-color-bright-blue                        ((t (:foreground ,yae_simple/base04 :background ,yae_simple/base04))))
     `(ansi-color-bright-magenta                     ((t (:foreground ,yae_simple/base06 :background ,yae_simple/base06))))
     `(ansi-color-bright-cyan                        ((t (:foreground ,yae_simple/base0F :background ,yae_simple/base0F))))
     `(ansi-color-bright-white                       ((t (:foreground ,yae_simple/base07 :background ,yae_simple/base07))))

;; ;;;; term and ansi-term)
;;      `(term                                         ((t (:foreground ,yae_simple/base05 :background ,yae_simple/base00))))
;;      `(term-color-black                             ((t (:foreground ,yae_simple/base02 :background ,yae_simple/base00))))
;;      `(term-color-white                             ((t (:foreground ,yae_simple/base05 :background ,yae_simple/base07))))
;;      `(term-color-red                               ((t (:foreground ,yae_simple/base08 :background ,yae_simple/base08))))
;;      `(term-color-yellow                            ((t (:foreground ,yae_simple/base0A :background ,yae_simple/base0A))))
;;      `(term-color-green                             ((t (:foreground ,yae_simple/base0B :background ,yae_simple/base0B))))
;;      `(term-color-cyan                              ((t (:foreground ,yae_simple/base0C :background ,yae_simple/base0C))))
;;      `(term-color-blue                              ((t (:foreground ,yae_simple/base0D :background ,yae_simple/base0D))))
;;      `(term-color-magenta                           ((t (:foreground ,yae_simple/base0E :background ,yae_simple/base0E))))

     ;; `(header-line                           ((t (:inherit default :background ,yae_simple/base00))))

     `(mode-line                             ((t (:inherit variable-pitch :foreground ,yae_simple/base00 :background ,yae_simple/base05 :box nil))))

     ;;; modeline
     `(mode-line-inactive ((t (:inherit variable-pitch :foreground ,yae_simple/base05 :background ,yae_simple/base03 :box nil))))
     `(mode-line-buffer-id ((t (:inherit variable-pitch :foreground ,(face-foreground 'region) :distant-foreground ,(face-background 'region)))))
	 ))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

;;;###autoload
(defun yae_simple-theme()
  "Load yae_simple-theme."
  (interactive)
  (load-theme 'yae_simple t))

(provide-theme 'yae_simple)

;;; yae_simple-theme.el ends here
